update charts

diff --git a/.github/workflows/app-pipeline.yaml b/.github/workflows/app-pipeline.yaml
--- a/.github/workflows/app-pipeline.yaml
+++ b/.github/workflows/app-pipeline.yaml
@@ -139,9 +139,24 @@ jobs:
       - name: Set EKS Kubeconfig 
         run: "aws eks update-kubeconfig --region $AWS_REGION --name golang-api-demo"
 
-      - name: Get API URL
+      - name: Test for API status code
         run: |
           URL=$(kubectl get services -n default golang-api --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')
+
+          # Test the LB URL until it's responding
+          attempt_counter=0
+          max_attempt=20
+
+          until $(curl --output /dev/null --silent --head --fail $URL); do
+              if [ ${attempt_counter} -eq ${max_attempts} ];then
+                echo "LB failed"
+                exit 1
+              fi
+
+              printf '.'
+              attempt_counter=$(($attempt_counter+1))
+              sleep 10
+          done
 
           response=$(curl -s -w "%{http_code}" $URL)
 
